name: Build and deploy Jekyll site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Ping search engines
        run: |
          curl "http://www.google.com/ping?sitemap=https://aielita2882-svg.github.io/sitemap.xml"
          curl "http://www.bing.com/ping?sitemap=https://aielita2882-svg.github.io/sitemap.xml"